function data = read_my_tiff(filename,n_images=1)
## usage: data = read_my_tiff(filename,n_images=1)
## function for reading 16bits uncompressed grayscale tiff images
## generated by SUMDD software or ImageJ1.46. It could not work in other tiff.
  warning off; 
  IMAGE_WIDTH=256;
  IMAGE_LENGTH=257;
  BITS_PER_SAMPLE=258;
  COMPRESSION=259;
  PHOTOMETRIC_INTERPRETATION=262;
  STRIP_OFFSETS=273;
  ROWS_PER_STRIP=278;
  STRIP_BYTE_COUNTS=279;
  X_RESOLUTION=282;
  Y_RESOLUTION=283;
  RESOLUTION_UNIT=296;

  fid = fopen (filename, "r");
  if (is_valid_file_id(fid))
    T = dec2hex(fread (fid,1,"uint16",0,"ieee-le"));
    if (T=="4949")
      TIFF_BYTE_ORDER="ieee-le";
    else 
      if (T=="4D4D")
        TIFF_BYTE_ORDER="ieee-be";
      endif
    endif
    TIFF_FILE_IDENTIFIER=fread (fid,1,"uint16",0,TIFF_BYTE_ORDER);
    if (TIFF_FILE_IDENTIFIER==42)
      [n_cols aux]=tiff_tag_read(filename,IMAGE_LENGTH);
      [n_rows aux]=tiff_tag_read(filename,IMAGE_WIDTH);
      data=zeros(n_rows,n_cols,length(n_images));
      for j=1:length(n_images)
        [data_offset aux]=tiff_tag_read(filename,STRIP_OFFSETS,n_images(j));
        if (data_offset!=0)
          fseek(fid,data_offset,SEEK_SET);
          [data(:,:,j) counts]=fread(fid,[n_rows n_cols],"uint16",0,TIFF_BYTE_ORDER);
        else 
          disp(strcat("there is no ", num2str(j), " IFD in tiff image."));
        endif
      endfor
    endif
  endif
  fclose (fid);
endfunction
